minus one cleep

diff --git a/drafts/crsh/crsh b/drafts/crsh/crsh
--- a/drafts/crsh/crsh
+++ b/drafts/crsh/crsh
@@ -3,7 +3,10 @@ echo '' >>/tmp/crsh-log
 echo 'STARTING NEW SESSION' >>/tmp/crsh-log
 echo '' >>/tmp/crsh-log
 
-sleep 2  # So that the fifos are initialized
+if [ ! -p /tmp/crsh-command ]; then
+  echo "command pipe not found" >/dev/stderr
+  exit 1
+fi
 
 echo "master will enter the loop" >>/tmp/crsh-log
 while true; do
